name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  app_links: ^4.0.1
  # cloud_firestore: ^4.17.4
  cloud_firestore: ^4.17.4
  dio: ^5.4.2
  firebase_app_installations: ^0.2.5+6
  firebase_core: ^2.31.1
  # firebase_installations: ^16.3.6
  # firebase_installations: ^16.3.6
  firebase_messaging: ^14.9.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0  
  flutter_secure_storage:
  get: ^4.6.6
  http: ^1.2.1
  image_picker: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  io: ^1.0.4
  shimmer: ^3.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.2.6
  url_strategy: ^0.2.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - lib/assets/images/
    - .env
